name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: _tea_utm_cache_2608=undefined; __tea_cookie_tokens_2608=%257B%2522user_unique_id%2522%253A%25227222844712410056229%2522%252C%2522web_id%2522%253A%25227222844712410056229%2522%252C%2522timestamp%2522%253A1759136212917%257D; sid_guard=67562abca60713f53f9b8bea1a15311c%7C1759993210%7C31536000%7CFri%2C+09-Oct-2026+07%3A00%3A10+GMT; uid_tt=864c0d5ea9855c904df02464db62c990; uid_tt_ss=864c0d5ea9855c904df02464db62c990; sid_tt=67562abca60713f53f9b8bea1a15311c; sessionid=67562abca60713f53f9b8bea1a15311c; sessionid_ss=67562abca60713f53f9b8bea1a15311c; session_tlb_tag=sttt%7C16%7CZ1YqvKYHE_U_m4vqGhUxHP_________AiOlwRjEF9-1M97w8uQfTLqcNKPHAy67OZu7cTu-WfPc%3D; is_staff_user=false; sid_ucp_v1=1.0.0-KDU1ZjRmMjIzY2VlZDc1OTlmNTE0NjJlMTM2NjAzM2IxY2M4MmI5ODgKFwiNpJCfv8zoARD6up3HBhiwFDgCQPEHGgJsZiIgNjc1NjJhYmNhNjA3MTNmNTNmOWI4YmVhMWExNTMxMWM; ssid_ucp_v1=1.0.0-KDU1ZjRmMjIzY2VlZDc1OTlmNTE0NjJlMTM2NjAzM2IxY2M4MmI5ODgKFwiNpJCfv8zoARD6up3HBhiwFDgCQPEHGgJsZiIgNjc1NjJhYmNhNjA3MTNmNTNmOWI4YmVhMWExNTMxMWM; csrf_session_id=90f474faedb5c267f3545be98ee28508
  COOKIE_2: ${{ secrets.COOKIE_2 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }}
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin

#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
