name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: __tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227222844712410056229%2522%252C%2522user_unique_id%2522%253A%25227222844712410056229%2522%252C%2522timestamp%2522%253A1681699589099%257D; _tea_utm_cache_2018={%22utm_source%22:%22gold_browser_extension%22}; _tea_utm_cache_2608={%22utm_source%22:%22gold_browser_extension%22}; sid_guard=86d7d4d74a8096a8189043a54f66234c%7C1713488269%7C31536000%7CSat%2C+19-Apr-2025+00%3A57%3A49+GMT; uid_tt=2a9d4997ed3e569a6733f90e6e7807f0; uid_tt_ss=2a9d4997ed3e569a6733f90e6e7807f0; sid_tt=86d7d4d74a8096a8189043a54f66234c; sessionid=86d7d4d74a8096a8189043a54f66234c; sessionid_ss=86d7d4d74a8096a8189043a54f66234c; sid_ucp_v1=1.0.0-KDM4NDgzMGRmM2RmNDgzZjUxYWRiZDBjOTkwZGUxMzdmZjI1OWQyMjQKFwiNpJCfv8zoARCNg4exBhiwFDgCQPEHGgJsZiIgODZkN2Q0ZDc0YTgwOTZhODE4OTA0M2E1NGY2NjIzNGM; ssid_ucp_v1=1.0.0-KDM4NDgzMGRmM2RmNDgzZjUxYWRiZDBjOTkwZGUxMzdmZjI1OWQyMjQKFwiNpJCfv8zoARCNg4exBhiwFDgCQPEHGgJsZiIgODZkN2Q0ZDc0YTgwOTZhODE4OTA0M2E1NGY2NjIzNGM; store-region=cn-gd; store-region-src=uid; csrf_session_id=90f474faedb5c267f3545be98ee28508
  COOKIE_2: __tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227218002049048151584%2522%252C%2522user_unique_id%2522%253A%25227218002049048151584%2522%252C%2522timestamp%2522%253A1680572067348%257D; _tea_utm_cache_2608={%22utm_source%22:%22gold_browser_extension%22}; _tea_utm_cache_2018={%22utm_source%22:%22gold_browser_extension%22}; csrf_session_id=90efb73a948b01c65395a5cfb71a69fd; passport_csrf_token=5dcca5773b42ee1cf7ce8b559ff6535e; passport_csrf_token_default=5dcca5773b42ee1cf7ce8b559ff6535e; n_mh=tl55ngZbCMzUelHfOUZG27iaebRJA0jDfIQnKn-AvOk; passport_auth_status=261223e3b679e1a65c97a9bfdc4fd5d9%2C; passport_auth_status_ss=261223e3b679e1a65c97a9bfdc4fd5d9%2C; sid_guard=21c77e9b32f616e98ad246bfb72e8f78%7C1712452154%7C31536000%7CMon%2C+07-Apr-2025+01%3A09%3A14+GMT; uid_tt=168de165fd6c06b021743a2256628264; uid_tt_ss=168de165fd6c06b021743a2256628264; sid_tt=21c77e9b32f616e98ad246bfb72e8f78; sessionid=21c77e9b32f616e98ad246bfb72e8f78; sessionid_ss=21c77e9b32f616e98ad246bfb72e8f78; sid_ucp_v1=1.0.0-KDc5ZTRjODkyMzVjZjc2OWI2NWVlOWZhMzZjZGViMTYxYTFjM2U0YjkKFwiopODamIykAxC65MewBhiwFDgCQPEHGgJobCIgMjFjNzdlOWIzMmY2MTZlOThhZDI0NmJmYjcyZThmNzg; ssid_ucp_v1=1.0.0-KDc5ZTRjODkyMzVjZjc2OWI2NWVlOWZhMzZjZGViMTYxYTFjM2U0YjkKFwiopODamIykAxC65MewBhiwFDgCQPEHGgJobCIgMjFjNzdlOWIzMmY2MTZlOThhZDI0NmJmYjcyZThmNzg; store-region=cn-gd; store-region-src=uid; msToken=n405grO28J559pbcpUk8YRzRJiFNtRMWiltzD6kUE_GCUp53M1wH-siD6ywoASrYF-C4triSprXaZve0d_ZcnF7ti9SLqLpf6kQ3l40wbHOrOkYAWBqkwttfWf5OSqk=
  COOKIE_3: ${{ secrets.COOKIE_3 }}
  COOKIE_4: ${{ secrets.COOKIE_4 }} 
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin

#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
