name: Auto

on:
  schedule:
    - cron: "30 22 * * *" # 北京时间上午06:30
  workflow_dispatch:

env:
  COOKIE: _tea_utm_cache_2018={%22utm_source%22:%22gold_browser_extension%22}; sid_guard=86d7d4d74a8096a8189043a54f66234c%7C1713488269%7C31536000%7CSat%2C+19-Apr-2025+00%3A57%3A49+GMT; uid_tt=2a9d4997ed3e569a6733f90e6e7807f0; uid_tt_ss=2a9d4997ed3e569a6733f90e6e7807f0; sid_tt=86d7d4d74a8096a8189043a54f66234c; sessionid=86d7d4d74a8096a8189043a54f66234c; sessionid_ss=86d7d4d74a8096a8189043a54f66234c; sid_ucp_v1=1.0.0-KDM4NDgzMGRmM2RmNDgzZjUxYWRiZDBjOTkwZGUxMzdmZjI1OWQyMjQKFwiNpJCfv8zoARCNg4exBhiwFDgCQPEHGgJsZiIgODZkN2Q0ZDc0YTgwOTZhODE4OTA0M2E1NGY2NjIzNGM; ssid_ucp_v1=1.0.0-KDM4NDgzMGRmM2RmNDgzZjUxYWRiZDBjOTkwZGUxMzdmZjI1OWQyMjQKFwiNpJCfv8zoARCNg4exBhiwFDgCQPEHGgJsZiIgODZkN2Q0ZDc0YTgwOTZhODE4OTA0M2E1NGY2NjIzNGM; store-region=cn-gd; store-region-src=uid; _tea_utm_cache_2608={%22utm_source%22:%22gold_browser_extension%22}; __tea_cookie_tokens_2608=%257B%2522user_unique_id%2522%253A%25227222844712410056229%2522%252C%2522web_id%2522%253A%25227222844712410056229%2522%252C%2522timestamp%2522%253A1735107407057%257D; csrf_session_id=90f474faedb5c267f3545be98ee28508
  COOKIE_2: __tea_cookie_tokens_2608=%257B%2522web_id%2522%253A%25227441938784705119753%2522%252C%2522user_unique_id%2522%253A%25227441938784705119753%2522%252C%2522timestamp%2522%253A1732711414112%257D; passport_csrf_token=e5627e6585e10d2743b3b99a974c4c32; passport_csrf_token_default=e5627e6585e10d2743b3b99a974c4c32; n_mh=tl55ngZbCMzUelHfOUZG27iaebRJA0jDfIQnKn-AvOk; sid_guard=0d7faa2153cffc83e313cd24e51b608e%7C1739755778%7C31536000%7CTue%2C+17-Feb-2026+01%3A29%3A38+GMT; uid_tt=cafb1b093a6a165a555136aa5cdab2e3; uid_tt_ss=cafb1b093a6a165a555136aa5cdab2e3; sid_tt=0d7faa2153cffc83e313cd24e51b608e; sessionid=0d7faa2153cffc83e313cd24e51b608e; sessionid_ss=0d7faa2153cffc83e313cd24e51b608e; is_staff_user=false; sid_ucp_v1=1.0.0-KGNhMjI2MjdhMThkZmQzNWVkZDY3MThlZGUxNzZhYzExMWM4YzEzYjgKFwiopODamIykAxCCosq9BhiwFDgHQPQHGgJsZiIgMGQ3ZmFhMjE1M2NmZmM4M2UzMTNjZDI0ZTUxYjYwOGU; ssid_ucp_v1=1.0.0-KGNhMjI2MjdhMThkZmQzNWVkZDY3MThlZGUxNzZhYzExMWM4YzEzYjgKFwiopODamIykAxCCosq9BhiwFDgHQPQHGgJsZiIgMGQ3ZmFhMjE1M2NmZmM4M2UzMTNjZDI0ZTUxYjYwOGU; store-region=cn-gd; store-region-src=uid; csrf_session_id=4c6f88bb718cdca691a291c5360ec592
  COOKIE_4: ${{ secrets.COOKIE_4 }} 
  COOKIE_5: ${{ secrets.COOKIE_5 }}
  EMAIL_USER: ${{ secrets.EMAIL_USER }}
  EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
  EMAIL_TO: ${{ secrets.EMAIL_TO }}
  DINGDING_WEBHOOK: ${{ secrets.DINGDING_WEBHOOK }}
  PUSHPLUS_TOKEN: ${{ secrets.PUSHPLUS_TOKEN }}
  WEIXIN_WEBHOOK: ${{ secrets.WEIXIN_WEBHOOK }}
  SERVERPUSHKEY: ${{ secrets.SERVERPUSHKEY }}
  FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}

jobs:
  CheckIn:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
      - name: Run Project
        run: |
          cd workflows
          yarn
          yarn checkin

#  SeaGold:
#    needs: CheckIn
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-node@v2
#      - name: Run Project
#        run: |
#          cd workflows
#          yarn
#          yarn seagold
